#!/bin/bash
USBDEV=`readlink -f $1`
read minor major < <(stat -c '%T %t' $USBDEV)
if [[ -z $minor || -z $major ]]; then
    echo "Error setting permissions for container: Device $1 not found"
    exit
fi
dminor=$((0x${minor}))
dmajor=$((0x${major}))
#CID=`docker ps --no-trunc -q --filter ancestor=$2|head -1`
CID=`docker ps --no-trunc | grep $2 | awk '{ print $1 }'|head -1`
if [[ -z $CID ]]; then
    echo "Error setting permissions for container: Container $2 not found"
    exit
fi
echo "Setting permissions to access $1 for container $2"
echo "c $dmajor:$dminor rwm" > /sys/fs/cgroup/devices/docker/$CID/devices.allow
